'use client'
import Image from 'next/image'
import { useEffect,useState } from 'react'
export interface PrototypePromo{ id:number;title:string;kicker?:string;text?:string;imageUrl?:string;linkUrl?:string }
export default function PrototypePromoCarousel({promos}:{promos:PrototypePromo[]}){const[index,setIndex]=useState(0);const[paused,setPaused]=useState(false);useEffect(()=>{if(paused||promos.length<2)return;const t=setInterval(()=>setIndex(i=>(i+1)%promos.length),9000);return()=>clearInterval(t)},[paused,promos.length]);if(!promos.length)return null;const active=promos[index];return <>
 <div className="pb-section-head"><div><div className="pb-kicker">Акции</div><h2 className="pb-h2">Что выгодно прямо сейчас</h2></div>{promos.length>1&&<div style={{display:'flex',alignItems:'center',gap:12}}><span style={{fontSize:11,fontWeight:600,letterSpacing:'.14em',color:'var(--pb-sub)'}}>{String(index+1).padStart(2,'0')} / {String(promos.length).padStart(2,'0')}</span><button className="pb-modal-close" onClick={()=>setIndex(i=>(i-1+promos.length)%promos.length)}>←</button><button className="pb-modal-close" style={{background:'var(--pb-ink)',color:'#fff'}} onClick={()=>setIndex(i=>(i+1)%promos.length)}>→</button></div>}</div>
 <div className="pb-section-grid" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)}>
  <a href={active.linkUrl||'#'} style={{gridColumn:'span 8',position:'relative',height:470,borderRadius:26,overflow:'hidden',border:'1px solid var(--pb-border)',background:'#E6E4E0'}}>
   {promos.map((p,i)=><div key={p.id} style={{position:'absolute',inset:0,opacity:i===index?1:0,transform:i===index?'none':'scale(1.02)',transition:'opacity 900ms cubic-bezier(.45,0,.15,1),transform 1200ms cubic-bezier(.45,0,.15,1)',zIndex:i===index?2:1}}>{p.imageUrl&&<Image src={p.imageUrl} alt={p.title} fill sizes="70vw" style={{objectFit:'cover'}}/>}</div>)}
   <div style={{position:'absolute',inset:0,zIndex:3,background:'linear-gradient(95deg,rgba(10,10,10,.86) 0%,rgba(10,10,10,.52) 54%,rgba(10,10,10,.08) 100%)'}}/>
   <div key={active.id} style={{position:'absolute',inset:0,zIndex:4,padding:30,display:'flex',flexDirection:'column',justifyContent:'space-between',color:'#fff'}}><span style={{alignSelf:'flex-start',padding:'7px 13px',borderRadius:999,background:'rgba(255,255,255,.16)',fontSize:10,fontWeight:600,letterSpacing:'.16em',textTransform:'uppercase',animation:'pbRise .56s var(--pb-ease) both'}}>{active.kicker||'Акция'}</span><div><div style={{fontSize:'clamp(28px,3.4vw,48px)',fontWeight:500,letterSpacing:'-.04em',lineHeight:1.02,maxWidth:'13ch',animation:'pbRise .62s var(--pb-ease) .06s both'}}>{active.title}</div>{active.text&&<div style={{marginTop:14,fontSize:14,lineHeight:1.5,color:'rgba(255,255,255,.78)',maxWidth:380}}>{active.text}</div>}</div></div>
  </a>
  <div className="pb-card" style={{gridColumn:'span 4',borderRadius:26,padding:14,display:'flex',flexDirection:'column',gap:4}}>{promos.map((p,i)=><button key={p.id} type="button" onClick={()=>setIndex(i)} style={{position:'relative',overflow:'hidden',flex:1,padding:'16px 18px',border:0,borderRadius:18,cursor:'pointer',display:'flex',alignItems:'center',gap:14,textAlign:'left',background:i===index?'#0A0A0A':'#F9F8F7',color:i===index?'#fff':'#0A0A0A'}}><span style={{fontSize:10,fontWeight:600,letterSpacing:'.14em',opacity:.5}}>{String(i+1).padStart(2,'0')}</span><div><div style={{fontSize:9.5,fontWeight:600,letterSpacing:'.15em',textTransform:'uppercase',opacity:.6}}>{p.kicker||'Акция'}</div><div style={{marginTop:6,fontSize:16,fontWeight:500,lineHeight:1.25}}>{p.title}</div></div>{i===index&&<span style={{position:'absolute',left:18,bottom:12,height:2,width:'calc(100% - 36px)',borderRadius:999,background:'rgba(255,255,255,.45)',transformOrigin:'left',animation:'pbBar 9000ms linear both'}}/>}</button>)}</div>
 </div>
 </>}