'use client'
import { useEffect,useRef,useState,type FormEvent } from 'react'
import Image from 'next/image'
import { useStore } from '@nanostores/react'
import { $cart,clearCart,removeFromCart,setItemQuantity } from '../stores/cart'
import { $selectedDates } from '../stores/dates'
import { calculateRentalDays,calculateRentalPrice,formatCurrency } from '../lib/pricing'
import { submitCheckout } from '../app/(frontend)/checkout/actions'
import PrototypeDatePicker,{type PrototypeDatePickerHandle} from './PrototypeDatePicker'

const EMAIL_RE=/^[^\s@]+@[^\s@]+\.[^\s@]+$/
function phone(raw:string){let d=raw.replace(/\D/g,'');if(d.startsWith('8'))d='7'+d.slice(1);if(!d.startsWith('7'))d='7'+d;d=d.slice(0,11);const r=d.slice(1);let o='+7';if(r.length)o+=` (${r.slice(0,3)}`;if(r.length>=3)o+=')';if(r.length>3)o+=` ${r.slice(3,6)}`;if(r.length>6)o+=`-${r.slice(6,8)}`;if(r.length>8)o+=`-${r.slice(8,10)}`;return o}
interface Promo{code:string;discountType:'percent'|'fixed';discountValue:number;minOrderAmount:number}
export default function PrototypeCheckout({openHour,closeHour}:{openHour:number;closeHour:number}){
 const storeCart=useStore($cart),storeDates=useStore($selectedDates);const[mounted,setMounted]=useState(false);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>setMounted(true),[]);const cart=mounted?storeCart:[];const dates=mounted?storeDates:{startDate:null,endDate:null}
 const datePickerRef=useRef<PrototypeDatePickerHandle>(null);const[name,setName]=useState(''),[email,setEmail]=useState(''),[phoneValue,setPhone]=useState(''),[contact,setContact]=useState(''),[comment,setComment]=useState(''),[agreeData,setAgreeData]=useState(false),[agreeTerms,setAgreeTerms]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState<string|null>(null),[orderId,setOrderId]=useState<number|null>(null),[promoInput,setPromoInput]=useState(''),[promo,setPromo]=useState<Promo|null>(null),[promoError,setPromoError]=useState<string|null>(null),[checking,setChecking]=useState(false)
 const hasRental=cart.some(i=>i.listingType==='rental'),hasDates=!hasRental||Boolean(dates.startDate&&dates.endDate);const days=dates.startDate&&dates.endDate?calculateRentalDays(dates.startDate,dates.endDate):1
 const lineTotal=(i:(typeof cart)[number])=>i.listingType==='sale'?i.price*i.quantity:calculateRentalPrice(i.price,dates.startDate||undefined,dates.endDate||undefined)*i.quantity
 const subtotal=hasDates?cart.reduce((s,i)=>s+lineTotal(i),0):cart.filter(i=>i.listingType==='sale').reduce((s,i)=>s+i.price*i.quantity,0)
 const promoAllowed=promo&&subtotal>=(promo.minOrderAmount||0);const discount=promoAllowed?Math.min(subtotal,promo!.discountType==='percent'?Math.round(subtotal*promo!.discountValue/100):promo!.discountValue):0;const total=Math.max(0,subtotal-discount)
 const ready=cart.length>0&&hasDates&&name.trim().length>1&&EMAIL_RE.test(email)&&phoneValue.replace(/\D/g,'').length===11&&agreeData&&agreeTerms&&!submitting
 const applyPromo=async()=>{const code=promoInput.trim();if(!code)return;setChecking(true);setPromoError(null);try{const r=await fetch(`/api/promo-codes/validate?code=${encodeURIComponent(code)}`);const data=await r.json();if(!r.ok||!data.valid){setPromo(null);setPromoError('Промокод недействителен');return}setPromo({code:data.code||code.toUpperCase(),discountType:data.discountType,discountValue:Number(data.discountValue)||0,minOrderAmount:Number(data.minOrderAmount)||0})}catch{setPromoError('Не удалось проверить промокод')}finally{setChecking(false)}}
 const submit=async(e:FormEvent)=>{e.preventDefault();setError(null);if(!ready)return;setSubmitting(true);try{const result=await submitCheckout({customerName:name.trim(),customerEmail:email.trim(),customerPhone:phoneValue,notes:[contact&&`Telegram / WhatsApp: ${contact}`,comment].filter(Boolean).join('\n')||undefined,promoCode:promo?.code,items:cart.map(i=>({productId:i.productId,quantity:i.quantity,startDate:i.listingType==='rental'?dates.startDate?.toISOString():undefined,endDate:i.listingType==='rental'?dates.endDate?.toISOString():undefined}))});if(!result.success){setError(result.errorCode==='RATE_LIMITED'?'Слишком много попыток. Попробуйте позже.':'Не удалось отправить заявку. Проверьте даты и наличие.');return}setOrderId(result.orderId||0);clearCart()}catch{setError('Не удалось отправить заявку.')}finally{setSubmitting(false)}}
 if(orderId!==null)return <div className="pb-container" style={{paddingTop:14,paddingBottom:80}}><div className="pb-card pb-success"><div className="pb-kicker">Готово</div><h2>Заявка отправлена!</h2><p>Заявка №{orderId}. Мы свяжемся с вами для подтверждения.</p></div></div>
 if(mounted&&cart.length===0)return <div className="pb-container" style={{paddingTop:14,paddingBottom:80}}><div className="pb-card pb-success"><div className="pb-kicker">Корзина</div><h2>Корзина пуста</h2><p>Добавьте технику из каталога.</p><a href="/catalog" className="pb-pill pb-btn" style={{marginTop:12}}>Перейти в каталог →</a></div></div>
 return <form id="checkout-form" onSubmit={submit} className="pb-page"><section className="pb-container pb-grid" style={{paddingTop:14,paddingBottom:80}}>
  <div className="pb-card pb-page-head"><h1 className="pb-h1">Заявка на аренду</h1><span style={{fontSize:13,color:'var(--pb-sub)'}}>{cart.reduce((s,i)=>s+i.quantity,0)} поз. · {hasRental?(hasDates?`${days} смен`:'выберите даты'):'покупка'}</span></div>
  <div className="pb-checkout-left">
   <div className="pb-card pb-check-card"><div className="pb-kicker">01 — Позиции</div>{cart.map(i=><div key={i.productId} className="pb-cart-line"><div className="pb-cart-thumb">{i.imageUrl?<Image src={i.imageUrl} alt={i.title} width={92} height={72}/>:<div className="pb-image-placeholder pb-image-placeholder-compact" aria-hidden="true"><svg viewBox="0 0 24 24" width="18" height="18"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="1.7"/><path d="m5 18 5-5 3.5 3 2.5-2.5 3 4.5"/></svg></div>}</div><div><div className="pb-cart-title">{i.title}</div><div className="pb-cart-sub">{formatCurrency(i.price)} / {i.unit}</div><div style={{marginTop:10,display:'flex',alignItems:'center',gap:14}}><div className="pb-qty"><button type="button" onClick={()=>setItemQuantity(i.productId,i.quantity-1)}>−</button><span>{i.quantity}</span><button type="button" onClick={()=>setItemQuantity(i.productId,i.quantity+1)}>+</button></div><button type="button" onClick={()=>removeFromCart(i.productId)} style={{border:0,background:'transparent',fontSize:10.5,fontWeight:600,letterSpacing:'.12em',textTransform:'uppercase',color:'var(--pb-sub)',cursor:'pointer'}}>Удалить</button></div></div><div style={{textAlign:'right'}}><div style={{fontSize:20,fontWeight:600,whiteSpace:'nowrap'}}>{hasDates||i.listingType==='sale'?formatCurrency(lineTotal(i)):'—'}</div><div style={{marginTop:6,fontSize:11,color:'var(--pb-sub)'}}>{i.listingType==='rental'?(hasDates?'свободно на ваши даты':'выберите даты'):'готово к покупке'}</div></div></div>)}</div>
   {hasRental&&<div className="pb-card pb-check-card"><div className="pb-date-section-head"><div className="pb-kicker">02 — Даты и время</div><button type="button" className="pb-date-edit" onClick={()=>datePickerRef.current?.open("from")}>Изменить</button></div><div className="pb-checkout-dates"><button type="button" onClick={()=>datePickerRef.current?.open("from")}><span>Выдача</span><strong>{dates.startDate?dates.startDate.toLocaleDateString("ru-RU",{day:"numeric",month:"long"}):"Выберите дату"}{dates.startDate?`, ${String(dates.startDate.getHours()).padStart(2,"0")}:00`:""}</strong></button><button type="button" onClick={()=>datePickerRef.current?.open("to")}><span>Возврат</span><strong>{dates.endDate?dates.endDate.toLocaleDateString("ru-RU",{day:"numeric",month:"long"}):"Выберите дату"}{dates.endDate?`, ${String(dates.endDate.getHours()).padStart(2,"0")}:00`:""}</strong></button></div><PrototypeDatePicker ref={datePickerRef} variant="hidden" openHour={openHour} closeHour={closeHour}/></div>}
   <div className="pb-card pb-check-card"><div className="pb-kicker">03 — Контакты</div><div className="pb-fields"><label className="pb-field"><span>Имя</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Как к вам обращаться"/></label><label className="pb-field"><span>Телефон</span><input value={phoneValue} onChange={e=>setPhone(phone(e.target.value))} placeholder="+7 (___) ___-__-__"/></label><label className="pb-field"><span>Email</span><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@example.com"/></label><label className="pb-field"><span>Telegram / WhatsApp</span><input value={contact} onChange={e=>setContact(e.target.value)} placeholder="@username"/></label><label className="pb-field" style={{gridColumn:'1 / -1'}}><span>Комментарий</span><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Что снимаете, нужна ли доставка"/></label></div></div>
  </div>
  <div className="pb-checkout-right"><div className="pb-card pb-check-card pb-sticky"><div className="pb-kicker">Итог</div><div style={{marginTop:12}}><div style={{display:'flex',justifyContent:'space-between',padding:'10px 0',fontSize:13.5}}><span style={{color:'var(--pb-sub)'}}>Позиций</span><span>{cart.reduce((s,i)=>s+i.quantity,0)} поз.</span></div>{hasRental&&<div style={{display:'flex',justifyContent:'space-between',padding:'10px 0',fontSize:13.5}}><span style={{color:'var(--pb-sub)'}}>Срок</span><span>{hasDates?`${days} смен`:'даты не выбраны'}</span></div>}<div style={{marginTop:8,display:'flex',gap:8}}><input value={promoInput} onChange={e=>{setPromoInput(e.target.value);setPromoError(null)}} disabled={Boolean(promo)} placeholder="Промокод" className="pb-search" style={{height:44}}/>{promo?<button type="button" className="pb-pill pb-btn pb-btn-light" style={{height:44}} onClick={()=>{setPromo(null);setPromoInput('')}}>Убрать</button>:<button type="button" className="pb-pill pb-btn pb-btn-light" style={{height:44}} disabled={checking||!promoInput.trim()} onClick={()=>void applyPromo()}>{checking?'…':'Применить'}</button>}</div>{promoError&&<p className="pb-red" style={{fontSize:12}}>{promoError}</p>}{promo&&<p style={{fontSize:12,color:promoAllowed?'var(--pb-sub)':'var(--pb-red)'}}>{promoAllowed?`✓ Промокод «${promo.code}» применён — скидка ${promo.discountType==='percent'?`${promo.discountValue}%`:formatCurrency(promo.discountValue)}.`:`Промокод действует от ${formatCurrency(promo.minOrderAmount)}.`}</p>}{discount>0&&<div style={{display:'flex',justifyContent:'space-between',padding:'10px 0',fontSize:13.5}}><span style={{color:'var(--pb-sub)'}}>Скидка</span><span className="pb-red">−{formatCurrency(discount)}</span></div>}<div className="pb-summary" style={{marginTop:10}}><span style={{fontSize:11,fontWeight:600,letterSpacing:'.13em',textTransform:'uppercase'}}>К оплате</span><strong>{hasDates?formatCurrency(total):'—'}</strong></div></div>
   <label className="pb-consent"><input id="agree-data" type="checkbox" checked={agreeData} onChange={e=>setAgreeData(e.target.checked)}/><span style={{fontSize:12.5,lineHeight:1.45,color:'var(--pb-copy)'}}>Согласен на обработку персональных данных</span></label><label className="pb-consent"><input id="agree-terms" type="checkbox" checked={agreeTerms} onChange={e=>setAgreeTerms(e.target.checked)}/><span style={{fontSize:12.5,lineHeight:1.45,color:'var(--pb-copy)'}}>Принимаю условия проката и договор аренды</span></label>{error&&<p className="pb-red" style={{fontSize:12.5}}>{error}</p>}<button type="submit" form="checkout-form" className="pb-submit" disabled={!ready}>{submitting?'Отправляем…':!name||!phoneValue?'Заполните имя и телефон':!agreeData||!agreeTerms?'Подтвердите согласия':'Отправить заявку'}</button><div style={{marginTop:12,fontSize:12,color:'var(--pb-sub)',textAlign:'center'}}>Перезвоним в течение 15 минут в рабочие часы.</div></div></div>
 </section></form>
}