import Link from 'next/link'
import Image from 'next/image'
import type { Category } from '../payload-types'
import { getCategories } from '../lib/data/categories'
import { getCategoryProductStats,getLowestRentalPrice,getProductTotals,getProducts } from '../lib/data/products'
import { getActivePromotions } from '../lib/data/promotions'
import { getSiteSettings } from '../lib/data/siteSettings'
import { getSubtreeIds } from '../lib/categoryTree'
import { mediaUrl } from '../lib/mediaUrl'
import { formatCurrency } from '../lib/pricing'
import PrototypeDatePicker from './PrototypeDatePicker'
import PrototypeProductCard from './PrototypeProductCard'
import PrototypePromoCarousel from './PrototypePromoCarousel'

export default async function PrototypeHome(){
 const [categories,featuredResult,totals,fromPrice,marqueeResult,settings,promotions,kitsResult]=await Promise.all([
  getCategories(),getProducts({limit:8,sort:'-lastSyncedAt'}),getProductTotals(),getLowestRentalPrice(),getProducts({limit:10,sort:'price',depth:0}),getSiteSettings(),getActivePromotions(),getProducts({isKit:true,limit:3})
 ])
 const featuredCategories=categories.filter(c=>c.parent==null).slice(0,6)
 const statIds=Array.from(new Set(featuredCategories.flatMap(c=>getSubtreeIds(c.id,categories))))
 const catStats=await getCategoryProductStats(statIds)
 const catMeta=(c:Category)=>{let count=0,min:number|undefined;for(const id of getSubtreeIds(c.id,categories)){const s=catStats.get(id);if(!s)continue;count+=s.count;min=min===undefined?s.minPrice:Math.min(min,s.minPrice)}return count&&min!==undefined?`${count} позиций · от ${formatCurrency(min)}`:''}
 const hero=mediaUrl(settings.heroBannerImage),heroMobile=mediaUrl(settings.heroBannerImageMobile)||hero
 const stats=[{value:String(totals.total),label:'Позиций в парке'},{value:String(totals.inStock),label:'Свободны сегодня'},{value:settings.depositLabel||'0 ₽',label:settings.depositCaption||'Залог'},{value:settings.pickupTimeLabel||'10 мин',label:settings.pickupTimeCaption||'Выдача по паспорту'}]
 const promos=promotions.map(p=>({id:p.id,title:p.title,kicker:p.kicker||undefined,text:p.text||undefined,imageUrl:mediaUrl(p.image),linkUrl:p.linkUrl||(p.slug?`/promotions/${p.slug}`:undefined)}))
 const contact={phone:settings.contactPhone||'+7 (996) 527-0026',telegram:settings.contactTelegram||'@Playbackrental_admin',address:settings.contactAddress||'г. Кемерово, ул. Демьяна Бедного, 6',hours:settings.contactHours||'10:00 — 21:00'}
 return <div className="pb-home">
  <section className="pb-container pb-grid pb-home-grid">
   <div className="pb-card pb-hero-copy"><div className="pb-hero-meta pb-kicker"><span>{settings.heroKicker||'Прокат съёмочной техники'}</span><span className="pb-city">{settings.heroCity||'Кемерово'}</span></div><h1 className="pb-hero-title">{settings.heroHeadline||'Техника для съёмки без залога'}</h1><div className="pb-rule"/><p className="pb-hero-text">{settings.heroSubtext||'Камеры, объективы, свет, звук и аксессуары. Выберите даты — каталог покажет доступные позиции.'}</p><div className="pb-flex-fill"/><div className="pb-actions"><Link href="/catalog" className="pb-pill pb-btn"><span>Смотреть каталог</span><span className="pb-icon-circle">→</span></Link><Link href="/catalog?type=kit" className="pb-pill pb-btn pb-btn-light">Готовые наборы</Link></div></div>
   <div className="pb-hero-side"><div className="pb-media pb-hero-media pb-hero-desktop">{hero&&<Image src={hero} alt="Playback Rental" fill priority sizes="40vw" style={{objectFit:'cover'}}/>}<div className="pb-media-caption"><span>Sony · Canon · GoPro</span><span className="pb-red">Fig. 01</span></div></div><div className="pb-media pb-hero-mobile">{heroMobile&&<Image src={heroMobile} alt="Playback Rental" fill priority sizes="calc(100vw - 24px)" style={{objectFit:'cover'}}/>}</div><PrototypeDatePicker variant="hero" openHour={settings.businessHoursOpen??10} closeHour={settings.businessHoursClose??21}/>{fromPrice!==undefined&&<div style={{fontSize:12.5,color:'var(--pb-sub)',padding:'0 8px'}}>Позиции от {formatCurrency(fromPrice)} · {categories.length} категорий</div>}</div>
   {stats.map((s,i)=><div key={s.label} className="pb-card pb-stat" style={{animationDelay:`${i*70}ms`}}><div className="pb-stat-value">{s.value}</div><div className="pb-stat-label">{s.label}</div></div>)}
   {marqueeResult.docs.length>0&&<div className="pb-marquee"><div className="pb-marquee-track">{[0,1].map(n=><div key={n} className="pb-marquee-row">{marqueeResult.docs.map(p=><span key={`${n}-${p.id}`} style={{display:'flex',gap:44,alignItems:'center'}}><span>{p.title}</span><span className="pb-red">◆</span></span>)}</div>)}</div></div>}
   {promos.length>0&&<PrototypePromoCarousel promos={promos}/>}
   {featuredCategories.length>0&&<><div className="pb-section-head"><div><div className="pb-kicker">Категории</div><h2 className="pb-h2">Выберите, чем снимать</h2></div><Link href="/catalog" className="pb-pill pb-btn pb-btn-light" style={{height:42}}>Весь каталог →</Link></div><div className="pb-section-grid">{featuredCategories.map((c,i)=>{const img=mediaUrl(c.image);return <Link key={c.id} href={`/catalog/${c.slug}`} className="pb-tile" style={{gridColumn:'span 4',animationDelay:`${i*60}ms`}}><div className="pb-tile-media">{img&&<Image src={img} alt={c.name} fill sizes="(min-width:1021px) 30vw,46vw" style={{objectFit:'cover'}}/>}<span className="pb-chip">{(c.slug||c.name).slice(0,4).toUpperCase()}</span></div><div className="pb-tile-body"><div><div className="pb-tile-title">{c.name}</div><div className="pb-tile-meta">{catMeta(c)}</div></div><span className="pb-arrow">→</span></div></Link>})}</div></>}
   {kitsResult.docs.length>0&&<><div className="pb-section-head"><div><div className="pb-kicker">Наборы</div><h2 className="pb-h2">Собрано под сценарий</h2></div><span style={{fontSize:13,color:'var(--pb-sub)'}}>Готовые комплекты техники</span></div><div className="pb-section-grid">{kitsResult.docs.map((p,i)=><div key={p.id} style={{gridColumn:'span 4'}}><PrototypeProductCard delay={i*60} product={{id:p.id,title:p.title,subtitle:p.subtitle,price:p.price,listingType:p.listingType,quantity:p.quantity,available:p.available,tag:p.tag,imageUrl:mediaUrl(p.images?.[0]),unit:p.listingType==='rental'?'набор / сутки':'шт.'}}/></div>)}</div></>}
   {featuredResult.docs.length>0&&<><div className="pb-section-head"><div><div className="pb-kicker">Берут чаще всего</div><h2 className="pb-h2">Популярные позиции</h2></div></div><div className="pb-section-grid">{featuredResult.docs.slice(0,4).map((p,i)=><div key={p.id} style={{gridColumn:'span 3'}}><PrototypeProductCard delay={i*45} product={{id:p.id,title:p.title,subtitle:p.subtitle,price:p.price,listingType:p.listingType,quantity:p.quantity,available:p.available,tag:p.tag,imageUrl:mediaUrl(p.images?.[0]),unit:p.listingType==='rental'?'смена / 24 часа':'шт.'}}/></div>)}</div></>}
   <div className="pb-dark-contact"><div><div className="pb-kicker" style={{color:'rgba(255,255,255,.5)'}}>Нужен совет</div><div style={{marginTop:16,fontSize:'clamp(26px,3.2vw,44px)',fontWeight:500,letterSpacing:'-.04em',lineHeight:1.02}}>Не знаете, что взять на съёмку?</div><p style={{marginTop:16,fontSize:14.5,lineHeight:1.55,color:'rgba(255,255,255,.62)',maxWidth:420}}>Опишите задачу — соберём комплект под неё и посчитаем стоимость на ваши даты.</p><Link href="/contact" className="pb-pill pb-btn" style={{marginTop:28,background:'#fff',color:'var(--pb-ink)'}}>Написать нам →</Link></div><div style={{display:'flex',flexDirection:'column',justifyContent:'flex-end',gap:8}}><div className="pb-contact-row"><span style={{color:'rgba(255,255,255,.55)'}}>Телефон</span><span>{contact.phone}</span></div><div className="pb-contact-row"><span style={{color:'rgba(255,255,255,.55)'}}>Telegram</span><span>{contact.telegram}</span></div><div className="pb-contact-row"><span style={{color:'rgba(255,255,255,.55)'}}>Адрес</span><span>{contact.address}</span></div><div className="pb-contact-row"><span style={{color:'rgba(255,255,255,.55)'}}>Часы</span><span>{contact.hours}</span></div></div></div>
  </section>
 </div>
}