import nextConfig from 'eslint-config-next'

// `@typescript-eslint/no-explicit-any` is enabled explicitly — turns out
// eslint-config-next never enabled it at all (confirmed by inspecting its
// own rule set), so the `legacyAnyPaths` scoped-off mechanism this file
// used to carry was a no-op the whole time: `any` was silently allowed
// everywhere, not just in the paths it named. Needs its own `plugins`
// entry, reusing the `@typescript-eslint` plugin instance eslint-config-next
// already registers (nextConfig[1]) rather than importing the package
// directly — it isn't hoisted as a direct dependency here.
//
// Every real `any` usage this surfaced (49, across apps/endpoints/admin
// view components/rental availability) was fixed or removed — 24 of them by
// deleting apps/cms/src/endpoints/admin/*.ts outright, which turned out to
// be dead code: apps/web was their only REST consumer, and apps/web no
// longer exists (docs/PLAN-next-migration.md Stage 4). No suppression left
// to carry.
const eslintConfig = [
  ...nextConfig,
  {
    // payload-types.ts is regenerated by `payload generate:types` (see
    // .gitignore) — not source we maintain. eslint-config-next's own
    // default ignores already cover .next/**, out/**, build/**, and
    // next-env.d.ts.
    ignores: ['src/payload-types.ts'],
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    plugins: { '@typescript-eslint': nextConfig[1].plugins['@typescript-eslint'] },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
]

export default eslintConfig
