import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat({ baseDirectory: import.meta.dirname })

// `no-explicit-any` is suppressed only in the paths that already carried
// `any` usage before this config existed (~190 uses, see next.config.mjs's
// removed `eslint.ignoreDuringBuilds` comment for the breakdown) — retyping
// that surface is separate follow-up work, not a blocker for turning lint
// on. Everything else, including any new (frontend)/(admin) route groups
// added by the Next.js migration, is linted at full strictness from day one.
const legacyAnyPaths = [
  'src/app/(payload)/**',
  'src/endpoints/**',
  'src/components/admin/**',
  'src/lib/rental/**',
]

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is regenerated by `next dev`/`next build` and its
    // triple-slash reference is required, not a style choice; payload-types.ts
    // is regenerated by `payload generate:types` (see .gitignore) — neither
    // is source we maintain.
    ignores: ['.next/**', 'next-env.d.ts', 'src/payload-types.ts'],
  },
  {
    files: legacyAnyPaths,
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
]

export default eslintConfig
